from scraper.scraper import ScraperOutput
from scraper.html_scraper import HTMLScraper
from scraper.rss_scraper import RSSScraper
from scraper.api_scraper import APIScraper
from scraper.hk01 import HK01Scraper
from scraper.stheadline import HeadlineScraper
from scraper.rthk_zh import RTHKChineseScraper
from scraper.rthk_en import RTHKEnglishScraper
from scraper.oncc import ONCCScraper
from scraper.scmp import SCMPScraper
from scraper.govhk import GovHKScraper
from scraper.c881903 import C881903Scraper
from scraper.weekendhk import WeekendHKScraper
from scraper.hket import HKETScraper
from scraper.orangenews import OrangeNewsScraper
from scraper.rfa import RFACantoneseScraper
from scraper.tvbnews import TVBNewsScraper
from scraper.nownews import NowNewsScraper
from scraper.unwire import UnwireScraper
from scraper.mingpao import MingPaoScraper
from scraper.am730 import AM730Scraper
from scraper.edigesthk import EdigestHKScraper
from scraper.ulifestyle import ULifestyleScraper
from scraper.thestandard import TheStandardScraper
from scraper.menclub import MenClubScraper
