on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t scrape . --file images/Dockerfile
      - name: Run Docker image
        run: |
          docker run --rm \
            -e R2_KEY_ID="${{ env.R2_KEY_ID }}" \
            -e R2_SECRET_KEY="${{ secrets.R2_SECRET_KEY }}" \
            -e R2_ACCOUNT_ID="${{ env.R2_ACCOUNT_ID }}" \
            -e R2_BUCKET_NAME="${{ env.R2_BUCKET_NAME }}" \
            scrape \
            archive.py \
            --day-ago 3  # Archive data from 3 days ago
