on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t container . --file images/Dockerfile
      - name: Run Docker image
        run: |
          docker run --rm \
            -e PIPELINE_ENDPOINT="${{ secrets.PIPELINE_ENDPOINT }}" \
            container \
            scrape.py
